### ISSUE TITLE
Build the 100K Wikipedia KB

### ISSUE THREAD

**Issue by hleborgne** [open-vision-language/infoseek#1]
The article says " we provide a 100K Wikipedia KB (articles and infobox images) that includes visual entities from INFOSEEK and top frequent entities from Wikipedia". However on the github page the 6M KB is provided only. And the paper reports the results on the KB with 100k articles only. 

How can we build the 100K (articles and infobox) KB to reproduce the experiments of the paper ?

**Comment by edchengg** [comment]
Hi @hleborgne, sorry about that. 
We couldn't provide the 100k KB data due to concern of affecting the fairness of OVEN-6M evaluation.
I would recommend reporting results using the 6M setting.
