### ISSUE TITLE
missing wikipedia images

### ISSUE THREAD

**Issue by dcaffo98** [open-vision-language/infoseek#2]
Thank you for this work and for releasing the code.
I've stumbled upon some issues while downloading INFOSEEK data.
My understanding is that the _entity_id_ field found within the _infoseek_train_withkb.jsonl_ and _infoseek_val_withkb.jsonl_ annotation files serves to match the _wikidata_id_ field in _Wiki6M_ver_1_0.jsonl_, so to retrieve some external knowledge useful to answer a given question.
In the **train** and **val** split, I count a total of 6741 unique entities id. However, only 2063 of the corresponding entries in _Wiki6M_ver_1_0.jsonl_ do have the _wikipedia_image_url_ field populated. Is there a way to collect the missing Wikipedia images? Furthermore, in the paper are reported also some models performances concerning the knowledge-based mode on the human and test split of INFOSEEK. But the annotation files of those splits lack the _enitity_id_ field, which should be required if one wants to check whether the retrieved entity is correct. Are these additional annotations available?

**Comment by edchengg** [comment]
Hi @dcaffo98 , thanks for your interests!

- missing wikipedia image url
We are using infobox image and unfortunately many entities do not actually have a wikipedia infobox `image`. Example of infobox: https://en.wikipedia.org/wiki/McDonnell_Douglas_MD-90

- missing entity_id for test/human set
This was intended as we want to prevent hacking test/human using gold entity_id or passages. We do provide answers for QA so people can evaluate the end performance on test/human.
We provide entity_id for the train/val set so people can train/eval retrieval models.

**Comment by dcaffo98** [comment]
Thank you @edchengg for the quick answer. 
From the [OVEN paper ](https://arxiv.org/abs/2302.11154)(sec. 5.1)
> When the Wikipedia entity does not have an infobox image, we use a black image to represent the visual support

Did you follow the same strategy, didn't you?

**Comment by dcaffo98** [comment]
Additionally, most URLs from _Wiki6M_ver_1_0.json_ result in an HTTP 404 error. Do you have a copy of the Wikipedia images from the 2022-10-03 dump?
On the other hand, can you release the checkpoint of the CLIP2CLIP entity recognition model?

**Comment by edchengg** [comment]
- _Did you follow the same strategy_
 Yes, it is similar to a placeholder zero tensor.

- _Copy of Wikipedia images_
Yes, you can find it in the [[contribute code](https://github.com/edchengg/oven_eval)] page by filling out a form to request - "all_wikipedia_images.tar" (30GB)

- _release the checkpoint of the CLIP2CLIP model_
We are not able to release this model. Another project [UniIR](https://tiger-ai-lab.github.io/UniIR/) is in the process of releasing a multimodal IR model that was fine-tuned on OVEN/InfoSeek. Stay tuned!

**Comment by duyc168** [comment]
Hi, I have a question about the entity_id in infoseek_train_withkb.jsonl and infoseek_val_withkb.jsonl. it seems that the entity id does not correspond to the Wiki6M_ver_1_0.jsonl, e.g., the entity_id Q178185 does not correspond to the 178185th entity in Wiki6M_ver_1_0.jsonl. so what does the entity_id in infoseek_train_withkb.jsonl and infoseek_val_withkb.jsonl mean to correspond to?

**Comment by edchengg** [comment]
> Hi, I have a question about the entity_id in infoseek_train_withkb.jsonl and infoseek_val_withkb.jsonl. it seems that the entity id does not correspond to the Wiki6M_ver_1_0.jsonl, e.g., the entity_id Q178185 does not correspond to the 178185th entity in Wiki6M_ver_1_0.jsonl. so what does the entity_id in infoseek_train_withkb.jsonl and infoseek_val_withkb.jsonl mean to correspond to?

the entity_id is corresponding to the id of the entity in a knowledge base called WikiData in the format “Q{***}”.
WikiData entity has a mapping to the Wikipedia page.
you can find the entity id inside wiki6m_ver_1_0 for each jsonl line.
