### ISSUE TITLE
KB mapping for the human set

### ISSUE THREAD

**Issue by Lackel** [open-vision-language/infoseek#4]
Hi, It is good work and I plan to do some research based on the dataset.

Could you please provide the KB mapping for the human set, so that I can measure the upper bound of model performance when given the correct external knowledge?

**Comment by edchengg** [comment]
Hi @Lackel ,
Thanks a lot for your interests!
We released withkb information for train/valid for model development.
For test/human set, the goal is to retrieve entity directly from the wikipedia. So we don't plan to release the gold withkb information publicly.
